export default Icons = {
    Homebg: require ("../assets/icons/bg.png"),
    HomeIcon: require('../assets/icons/Home.png'),
    TargetIcon: require('../assets/icons/Target.png'),
    ReportIcon: require('../assets/icons/Report.png'),
    LogsIcon: require('../assets/icons/Logs.png'),
    SettingIcon: require('../assets/icons/Setting.png'),
    TargetDeactive: require('../assets/icons/TargetDeactive.png'),
    ReportDeactive: require('../assets/icons/ReportDeactive.png'),
    LogsDeactive: require('../assets/icons/LogsDeactive.png'),
    SettingDeactive: require('../assets/icons/SettingDeactive.png'),
    eyes_hide: require('../assets/icons/eyes_hide.png'),
    back_arrow: require('../assets/icons/left.png'),
    logout: require('../assets/icons/PowerOff.png'),
    face_lock: require('../assets/icons/face_lock.png'),
    indicator: require('../assets/icons/indicator.png'),
    Signal_Arrow: require('../assets/icons/signal.png'),
    eyes_show: require('../assets/icons/eyes.png'),
    thumbsup: require('../assets/icons/Buy_icon.png'),
    greenDot: require('../assets/icons/greenDot.png'),
    DotG: require('../assets/icons/DotG.png'),
    DotR: require('../assets/icons/DotR.png'),
    UpTrend: require('../assets/icons/UpTrend.png'),
    DownTrend: require('../assets/icons/DownTrend.png'),
    AMC_show: require ('../assets/icons/amc.png'),
    AFRM_show: require ('../assets/icons/afrm.png'),
    coin_show: require ('../assets/icons/coin.png'),
    MARA_show: require ('../assets/icons/mara.png'),
    Cross_show: require ('../assets/icons/cross.png'),
    Cross_show: require ('../assets/icons/cros.png'),
    Greenline_show: require ('../assets/icons/greenline.png'),
    Redline_show: require ('../assets/icons/redline.png'),
    Sale_show: require ('../assets/icons/Sale_icon.png'),
    left: require('../assets/icons/left.png'),
    search: require('../assets/icons/search.png'),
    fav: require('../assets/icons/fav.png'),
    un_fav: require('../assets/icons/un_fav.png'),
    hideeye: require('../assets/icons/hideeye.png'),
    amc2: require('../assets/icons/amc2.png'),
    PuseShow : require('../assets/icons/puse.svg'),
    downarrow : require('../assets/icons/downarrow.png'),
    recordbutton : require('../assets/icons/recordbutton.png'),
    warningShow : require('../assets/icons/warning.png'),
    pauseShow : require('../assets/icons/pause.png'),
    historyShow : require('../assets/icons/history.png'),
    crosShow : require('../assets/icons/cros.png'),
    Splash : require('../assets/icons/Splash.png'),
    Logo : require('../assets/icons/Logo.png'),
    GetStarted : require('../assets/icons/GetStarted.png'),
    Shuttle : require('../assets/icons/Shuttle.png'),
    HomeNew : require('../assets/icons/new.png'),
}